# Generated by Django 5.1.7 on 2025-03-16 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_tasktable_assigned_to_alter_tasktable_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktable',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('I', 'In Progress'), ('C', 'Completed'), ('A', 'Archived')], default='I', max_length=1),
        ),
    ]
